### ISSUE TITLE
Add naming to intro-doc and readme

### ISSUE THREAD

**Issue by pfrazee** [ssbc/docs#11]
There's no reference for how to set names from the CLI. Pubs frequently need that, so add it to the docs.

**Comment by aredridel** [comment]
I was just coming here to find this information!

**Comment by pfrazee** [comment]
Yeah, sorry! Forgot I hadnt hit this yet. It's:

```
sbot publish --type about --about {feedId} --name {name}
```

**Comment by aredridel** [comment]
Awesome!

**Comment by aredridel** [comment]
Hm. Feed ID would be something like `@WzvzUh2KMhAfWeJEpkI01BGlTtLXOei7GoB/dLVjcjE=.ed25519` ?

**Comment by pfrazee** [comment]
Correct. They always start with an `@` symbol. (Messages start with a `%`, and blobs start with a `&`)

**Comment by aredridel** [comment]
Woo! `polis.nbtsc.org` is now a pub server!

... also: turns out, ooooold scuttlebot will happily wipe it `~/.ssb/secret` and replace it with k256 keys. Good times. Accidentally ran that. It erased my current key.

**Comment by pfrazee** [comment]
> Woo! polis.nbtsc.org is now a pub server!

Yay!

> ... also: turns out, ooooold scuttlebot will happily wipe it ~/.ssb/secret and replace it with k256 keys. Good times. Accidentally ran that. It erased my current key.

Oh no! Sorry about that :(

**Comment by aredridel** [comment]
Oh, well! Excised the old version from my server and memory :)

**Comment by pfrazee** [comment]
Cool :)

**Comment by aredridel** [comment]
This should be fixed by #13
