### ISSUE TITLE
incorrect documentation: adding a blob

### ISSUE THREAD

**Issue by dominictarr** [ssbc/docs#15]
@nhq found that adding blobs doesn't match the documentation. What we have is correct if you embed scuttlebot, but not if you use the client.

To use the current api, you need to calculate the hash yourself.

``` js
function createHash() {
  var hash = crypto.createHash('sha256'), hasher
  return hasher = pull.through(function (data) {
    hash.update(data)
  }, function () {
    hasher.digest = '&'+hash.digest('base64')+'.sha256'
  })
}
var hasher = createHash()
pull(
   toPull.source(fileStream),
   hasher,
    sbot.blobs.add(function (err) {
      hasher.digest //here is the hash.
     })
)
```

The better solution would be to update muxrpc to send the value in the callback in a sink stream.

**Comment by dominictarr** [comment]
Having investigated this a little further I have decided that making that change to muxrpc would introduce considerable complexification... having that change will mean that you get a write ack after a write stream - not just writing it to the connection, but writing to the remote database. That will probably turn out to be a very good idea one day... But it would also be quite a bit of work.

**Comment by pfrazee** [comment]
Ok. What about using duplex streams?

**Comment by dominictarr** [comment]
It would be simple enough to make it a duplex stream... I was thinking make a special duplex syntax where if you pass it a callback it would put the duplex data into that... and maybe error if it wrote more than one messages. A duplex stream on it's own would work, but would be more awkward.

**Comment by pfrazee** [comment]
That sounds good to me

**Comment by dominictarr** [comment]
I guess you could use it with a `pull.one(function (err, data) { })` that would read a single value and error (aborting the source) if there was more than one.

**Comment by dominictarr** [comment]
we could do that without actually making any changes to muxrpc.

**Comment by pfrazee** [comment]
Can we make calls to duplexes in muxrpc do that, automatically, if a cb is given as the last param?

**Comment by dominictarr** [comment]
That was what I was thinking.

**Comment by pfrazee** [comment]
:+1:

**Comment by NHQ** [comment]
:man_with_gua_pi_mao:
