### ISSUE TITLE
You can get help with -h.

### ISSUE THREAD

**Issue by mixmix** [ssbc/docs#7]
no you can't 

installed with `npm install -g scuttlebot` 
then running `sbot -h`
gives : `Invalid command`

propose there is an `sbot --help` option.
_I might take a stab at a pull request for it if I can find the relevant files._

**Comment by mixmix** [comment]
reference : https://github.com/ssbc/docs#install-scuttlebot

**Comment by pfrazee** [comment]
What version of scuttlebot are you running? (Type `sbot version`). The current version (7.3.0) has full live help, and (for me) will output it if you do either `sbot`, `sbot -h`, or `sbot --help`.

**Comment by mixmix** [comment]
![](https://i.imgur.com/9u4PMPo.png)

nope

**Comment by mixmix** [comment]
I get the same results with the sbot I've just built from my pull request (7.3.0)

I'm trying `npm install -g scuttlebutt` in the hopes that I get a newer version ?
nope, exactly the same. Is there anything else I might have missed ?

**Comment by pfrazee** [comment]
What server are you running? Do you possibly have patchwork running?

**Comment by pfrazee** [comment]
I bet that's what's happening. Patchwork embeds scuttlebot 7.0.2. The version command is actually outputting the cli client's version, not the server version. We should make it output the server version.

**Comment by mixmix** [comment]
yes I am.. good catch, I thought the system would treat them differently (I don't understand that magic yet)

![](https://i.imgur.com/zBJEhEe.png)

**Comment by mixmix** [comment]
(that's what happened when I stopped patchwork)

how misleading

**Comment by pfrazee** [comment]
Yeah, we don't have a satisfactory setup for this yet, because our plans are wrapped up in Brickhouse, which isn't ready yet.

For a non-brickhouse solution. I don't want Patchwork to embed a Scuttlebot, I'd rather it use an outside sbot as a server. 

Related issues:
- https://github.com/ssbc/scuttlebot/issues/238
- https://github.com/ssbc/scuttlebot/issues/243

**Comment by pfrazee** [comment]
Ok, I created https://github.com/ssbc/scuttlebot/issues/250 to address some of the confusion we had here, and we have standing issues to deal with how patchwork and sbot's relationships need to be made simpler and more clear.

Closing this issue.

**Comment by mixmix** [comment]
Sweet, thanks for that. And thanks for taking time to respond to me
muddling around all up  here

**Comment by pfrazee** [comment]
No sweat, sorry for the trouble here. This is a nasty spot I'm trying to solve.

**Comment by mixmix** [comment]
:pineapple:
Keep up the good work

**Comment by dominictarr** [comment]
@pfraze what is stopping patchwork from embedding the latest version of scuttlebot?

**Comment by pfrazee** [comment]
Nothing, just need to update it. What I want to do, though, is not embed sbot, because it's not a repeatable pattern in other applications (unless they maintain a separate data directory)

**Comment by dominictarr** [comment]
yes. I think it's a reasonable special case though, during the brickhouse bootstrapping process
